# Generated by Django 2.2.2 on 2019-06-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuallistinformation',
            name='price',
            field=models.IntegerField(max_length=250),
        ),
    ]
