# Generated by Django 2.2.2 on 2019-06-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190621_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuallistinformation',
            name='price',
            field=models.IntegerField(),
        ),
    ]
