# Generated by Django 2.2.2 on 2019-06-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190621_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuallistinformation',
            name='house_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='individuallistinformation',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
